export const RESET_STORE = 'RESET_STORE';
export const CHANGE_TEMPLATE_CONFIGURATION = 'CHANGE_TEMPLATE_CONFIGURATION';
export const CREATE_TEMPLATE_LOAD_SUCCESS = 'CREATE_TEMPLATE_LOAD_SUCCESS';
export const CREATE_TEMPLATE_LOAD_FAIL = 'CREATE_TEMPLATE_LOAD_FAIL';
export const CREATE_TEMPLATE_SHOW_SPINNER = 'CREATE_TEMPLATE_SHOW_SPINNER';

